# Generated by Django 2.0.2 on 2018-04-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('body', models.TextField(verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
