# Generated by Django 2.0.2 on 2018-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
