# Generated by Django 2.0.2 on 2018-04-15 09:44

from django.db import migrations
from django.apps import apps

def subscription_seed(apps, schema_editor):
    SubModel = apps.get_model('store', 'SubscriptionModel')
    SubModel = SubModel.objects
    SubModel.create(name='Free Trial', price='0', length='14')
    SubModel.create(name='Monthly', price='5', length='1')
    SubModel.create(name='3 Months', price='15', length='3')
    SubModel.create(name='6 Months', price='30', length='6')
    SubModel.create(name='12 Months', price='60', length='12')



class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(subscription_seed),
    ]
