# Generated by Django 2.0.2 on 2018-05-04 12:40

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GotapTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=255)),
                ('ammount', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('statement_descriptor', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('paid', models.BooleanField()),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnetTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.CharField(max_length=10)),
                ('currencrycode', models.CharField(max_length=3)),
                ('paymentid', models.CharField(max_length=16)),
                ('result', models.CharField(blank=True, max_length=30)),
                ('auth', models.CharField(blank=True, max_length=255)),
                ('ref', models.CharField(blank=True, max_length=255)),
                ('postdate', models.DateField(blank=True)),
                ('transid', models.CharField(blank=True, max_length=14)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('reponse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(db_index=True, max_length=16, unique=True)),
                ('GotapTransactions', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GoTapTransactions', to='payment.GotapTransactions')),
                ('KnetTransactions', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KnetTransactions', to='payment.KnetTransactions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
