# Generated by Django 2.0.2 on 2018-05-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='GotapTransactions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GotapTransactions', to='payment.GotapTransactions'),
        ),
    ]
