# Generated by Django 2.0.2 on 2018-05-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_gotaptransactions_urlreponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gotaptransactions',
            old_name='urlreponse',
            new_name='urlresponse',
        ),
    ]
