# Generated by Django 2.0.2 on 2018-05-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20180506_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='subscription_updated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
