# Generated by Django 2.0.2 on 2018-05-09 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20180508_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knettransactions',
            old_name='currencrycode',
            new_name='currencycode',
        ),
    ]
