# Generated by Django 2.0.2 on 2018-05-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20180509_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knettransactions',
            name='postdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
