# Generated by Django 2.0.2 on 2018-05-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20180509_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knettransactions',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
