# Generated by Django 2.0.2 on 2018-05-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20180509_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knettransactions',
            name='transid',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
